#!/usr/bin/env python3

import argparse
import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from core import llm                     # noqa: E402
from core.languages import (             # noqa: E402
    AUDIENCE_INSTRUCTION,
    LANG_EXPERIMENTAL,
    LANG_INSTRUCTION,
)
from core.paths import PRESET_DIR        # noqa: E402
from core.slides import list_refine_models, list_vision_models  # noqa: E402

ACTION_EXPLANATION = {
    "skip": "keeps the raw OCR text as-is, no refine pass runs",
    "clean": "fixes OCR mistakes and formatting, wording and content stay untouched",
    "summary": "compresses content into concise, scannable study notes",
    "deep": "expands content into a full book-style document with explanations and examples",
}


# ── interactive prompts ─────────────────────────────────────
def ask_model(models: list[str], label: str, purpose: str) -> str:
    print(f"\n{label}?")
    print(f"({purpose})")
    for i, m in enumerate(models, 1):
        print(f"  {i}. {m}")
    print("[default: 1]")
    choice = input(">>> ").strip() or "1"
    try:
        return models[int(choice) - 1]
    except (ValueError, IndexError):
        print(f"[warn] invalid choice, using {models[0]}")
        return models[0]


def ask_action() -> str:
    print("""
Refine action? (
  1. skip - do nothing
  2. clean - fix OCR mess only
  3. summary - compress into notes
  4. deep - structured + analogy + understanding
) [default: skip]""")
    choice = input(">>> ").strip() or "1"
    action = {"1": "skip", "2": "clean", "3": "summary", "4": "deep"}.get(choice, "skip")
    print(f"[info] {action} — {ACTION_EXPLANATION[action]}")
    return action


def ask_language() -> str:
    codes = list(LANG_INSTRUCTION.keys())
    print(f"\nLanguage for compiled output? ({' / '.join(codes)}) [default: auto]")
    lang = input(">>> ").strip().lower() or "auto"
    if lang not in LANG_INSTRUCTION:
        print(f"[warn] unknown language '{lang}', using auto")
        lang = "auto"
    print(f"[info] output will be written in {LANG_INSTRUCTION[lang]}")
    if lang in LANG_EXPERIMENTAL:
        print(f"[warn] '{LANG_INSTRUCTION[lang]}' output quality depends on the refine model's proficiency in this language. Results may vary.")
    return lang


def ask_level() -> str:
    print("""
Audience level? (
  1. beginner - explain from scratch
  2. intermediate - some familiarity assumed
  3. advanced - skip basics, focus on nuance
) [default: intermediate]""")
    choice = input(">>> ").strip() or "2"
    level = {"1": "beginner", "2": "intermediate", "3": "advanced"}.get(choice, "intermediate")
    print(f"[info] {level} — {AUDIENCE_INSTRUCTION[level]}")
    return level


def ask_filename() -> str:
    print("\nPreset filename? (saved to presets/<name>.toml)")
    name = input(">>> ").strip() or "custom"
    if not name.endswith(".toml"):
        name += ".toml"
    return name


# ── output ───────────────────────────────────────────────────
def build_toml(vision_model: str, refine_model: str | None, action: str, lang: str, level: str) -> str:
    lines = [
        "# generated by preset-generator.py, trigger with: python index.py <file.pdf> --preset <name>.toml",
        f'vision_model = "{vision_model}"',
    ]
    if refine_model:
        lines.append(f'refine_model = "{refine_model}"')
    lines.append(f'action = "{action}"      # clean | summary | deep | skip')
    lines.append(f'lang = "{lang}"          # en | id | original | etc.')
    lines.append(f'level = "{level}"   # beginner | intermediate | advanced')
    return "\n".join(lines) + "\n"


def parse_args():
    parser = argparse.ArgumentParser(description="Interactively build a preset TOML for index.py")
    parser.add_argument("-o", "--output", type=str, metavar="FILE", help="Preset filename, skips the filename prompt")
    return parser.parse_args()


def main():
    args = parse_args()

    try:
        vision_models = asyncio.run(list_vision_models())
    except llm.LLMError as e:
        print(f"[error] {e}")
        exit(1)
    if not vision_models:
        print("[error] no vision models found. check OCR_MODEL_KEYWORDS.")
        exit(1)
    vision_model = ask_model(vision_models, "Vision model", "used to OCR text out of each slide image")

    action = ask_action()

    refine_model = None
    if action != "skip":
        refine_models = asyncio.run(list_refine_models())
        if not refine_models:
            print("[error] no refine models found. check REFINE_MODEL_KEYWORDS.")
            exit(1)
        refine_model = ask_model(refine_models, "Refine model", "used to clean, summarize, or expand the raw OCR text")

    lang = ask_language()
    level = ask_level()

    toml_text = build_toml(vision_model, refine_model, action, lang, level)

    print(f"\n{toml_text}")

    filename = args.output or ask_filename()
    if not filename.endswith(".toml"):
        filename += ".toml"

    PRESET_DIR.mkdir(exist_ok=True)
    out_path = PRESET_DIR / filename
    if out_path.exists():
        confirm = input(f"\n[warn] {out_path.name} already exists, overwrite? (y/N): ").strip().lower()
        if confirm != "y":
            print("[cancelled]")
            exit(0)

    out_path.write_text(toml_text)
    print(f"\n[output] preset saved → {out_path}")


if __name__ == "__main__":
    main()
